openapi: 3.0.3
info:
  title: Magickr
  description: "API to interact with the magickr services"
  version: 0.0.1
servers:
  - url: 'https'
paths:
  /auth/login:
    post:
      summary: "Login an user using credentials"
      operationId: userLogin
      tags:
        - security
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginWithCredentials'
      responses:
        '200':
          description: "JWT Token"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
components:
  schemas:
    LoginWithCredentials:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    User:
      type: object
      required:
        - id
        - name
        - lastName
        - email
        - birthdate
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        lastName:
          type: string
        email:
          type: string
        birthdate:
          type: string
    Token:
      type: object
      required:
        - token
      properties:
        token:
          type: string
